### ISSUE TITLE
[feature request] export pure component option

### ISSUE THREAD

**Issue by jtrein** [sussol/sussol-react-table#12]
A pure component would help solve the issue of the component tree updating every time a `setState()` is called inside the parent.

I have spiked this and it works well. When the `tableData` is changed, or any other props change on the pure version, the component renders as expected.

A higher order component that wraps the normal export will be the easiest path to take.

**Comment by Chris-Petty** [comment]
Why not just make the target component extend PureComponent?

**Comment by jtrein** [comment]
Could. If you're cool with it I am. Thought an optional export might be better.

**Comment by jtrein** [comment]
Let's just do this. We're technically the only ones using this.
